---

- name: config > Ensure directory exist
  file:
    path: "{{ elao_logentries_config_file|dirname }}"
    state: directory
    recurse: yes
    owner: root
    group: root
    mode: 0755

- name: config > Config
  template:
    src:  "{{ elao_logentries_config_template }}"
    dest: "{{ elao_logentries_config_file }}"
  notify:
    - logentries restart
